# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:16-alpine # Alterado para a versão 16
    restart: always
    environment:
      POSTGRES_DB: smarttranslate_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: